require File.expand_path(File.dirname(__FILE__) + '/all_mocks.rb')
require File.expand_path(File.dirname(__FILE__) + '/../webfontAPI.rb')
require File.expand_path(File.dirname(__FILE__) + '/webfonts_spec.rb')
require File.expand_path(File.dirname(__FILE__) + '/webfontsAccountConfig_spec.rb')
require File.expand_path(File.dirname(__FILE__) + '/mock_AUTH_spec.rb')
require File.expand_path(File.dirname(__FILE__) + '/mock_REST_spec.rb')
