require '../webfontAPI.rb'
#require 'hash_HMAC_spec.rb'
#require 'auth_header_spec.rb'
#require 'mock_url_retriever.rb'
#require 'mock_domain_parser.rb'
require 'webfonts_spec.rb'
#require 'mock_session.rb'
#require 'patron_wrapper_spec.rb'
#require 'domain_parser_spec.rb'
#
